"""empty message

Revision ID: cd655e9d2204
Revises: 3b2b2d4fc921
Create Date: 2020-03-01 20:25:49.835809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd655e9d2204'
down_revision = '3b2b2d4fc921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('areacode', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'areacode')
    # ### end Alembic commands ###
