"""202003011503

Revision ID: 12ee59a0b748
Revises: 1537c2c66315
Create Date: 2020-03-01 15:03:33.365223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ee59a0b748'
down_revision = '1537c2c66315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('create_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'country')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
