"""first

Revision ID: 687288d8aa7f
Revises: 
Create Date: 2020-02-29 16:46:12.872274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687288d8aa7f'
down_revision = None
branch_labels = None
depends_on = None

# TODO: 更新数据库
# TODO: 命令：alembic upgrade head
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

# TODO: 降级数据库
# TODO: 命令：alembic downgrade head
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
