"""add

Revision ID: a21679f2daac
Revises: 687288d8aa7f
Create Date: 2020-02-29 16:57:45.332254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21679f2daac'
down_revision = '687288d8aa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('create_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'age')
    op.drop_column('article', 'create_time')
    # ### end Alembic commands ###
