"""202003011352

Revision ID: 443352183c19
Revises: f1cfb42b4574
Create Date: 2020-03-01 13:52:34.407237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443352183c19'
down_revision = 'f1cfb42b4574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('create_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    op.drop_column('user', 'country')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
