"""empty message

Revision ID: 69884cd3703b
Revises: 72695e838965
Create Date: 2020-03-07 17:41:40.247816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69884cd3703b'
down_revision = '72695e838965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=30), nullable=False))
    op.alter_column('user', 'money',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'money',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
